### ISSUE TITLE
[Bug] Does not issue Pali Wallet signature request when PaliWallet is locked.

### ISSUE THREAD

**Issue by osiastedian** [osiastedian/syscoin-bridge#1]
Steps:

1. Go to `https://syscoin-bridge.vercel.app/`
2. Connect "PaliWallet"
3. Connect "Metamask"
4. Click "Continue"
5. Input `0.1` on the form
6. Open PaliWallet and Lock it
7. Click "Start Transfer"

Actual Result:

1. Moves state to "Burn Sys"
2. Pali Wallet does nothing. No signature request is issued.

Expected Result:

1. Should prompt user to connect PaliWallet
2. Should prompt for Signature Request

**Comment by sidhujag** [comment]
It properly prompts to connect to Pali but after connecting it does not prompt for signature request until i hit the retry messag
<img width="1273" alt="Screen Shot 2022-08-10 at 1 13 02 PM" src="https://user-images.githubusercontent.com/6238042/184011453-b9104dd2-0b50-432f-b645-9a7f74647a58.png">
e

**Comment by osiastedian** [comment]
@sidhujag 

Demo video with the recent fix

https://user-images.githubusercontent.com/11253903/184265743-25b22ac7-9327-4825-ba1e-ba9352b15f33.mov

**Comment by sidhujag** [comment]
on my wizard it says account is connected then doesn't show signature

**Comment by sidhujag** [comment]
<img width="1339" alt="Screen Shot 2022-08-11 at 6 38 09 PM" src="https://user-images.githubusercontent.com/6238042/184269572-391f9b39-9543-4073-a48b-6573af583780.png">
FIRST IT ASKS TO UNLOCK

**Comment by sidhujag** [comment]
<img width="374" alt="Screen Shot 2022-08-11 at 6 38 20 PM" src="https://user-images.githubusercontent.com/6238042/184269613-3070e3e9-bf09-4be4-b90b-9112b2e05f9a.png">
THEN IT UNLOCKS THEN SAYS ACCOUNT CONNECTED

**Comment by sidhujag** [comment]
<img width="1261" alt="Screen Shot 2022-08-11 at 6 38 33 PM" src="https://user-images.githubusercontent.com/6238042/184269653-0a54b659-d7b2-4668-a97a-43e22e3decac.png">
THEN ON DAPP IT NEVER BOTHERS TO TRY TO OPEN SIGN AGAIN IT THINKS IT SIGNED BUT IT DIDNT

**Comment by sidhujag** [comment]
> @sidhujag
> 
> Demo video with the recent fix
> 
>  Issue.1.Demo.mov

I did this exact step and got the issue as I screenshotted, I am on Pali 1.0.28 (chrome, osx) which one are you?

**Comment by sidhujag** [comment]
Maybe we do an extra check if not signed (can we detect this?) to ask for pali sign again assuming it has hit this issue so it will auto-popup again if signature has not been signed, not sure if this is detectable or not.

**Comment by osiastedian** [comment]
> > @sidhujag
> > Demo video with the recent fix
> > Issue.1.Demo.mov
> 
> I did this exact step and got the issue as I screenshotted, I am on Pali 1.0.28 (chrome, osx) which one are you?

Here are my environments.

<img width="1624" alt="Screen Shot 2022-08-12 at 10 04 48 AM" src="https://user-images.githubusercontent.com/11253903/184271733-5b52fffe-c17c-48c6-8227-79559cba0246.png">
<img width="1624" alt="Screen Shot 2022-08-12 at 10 04 59 AM" src="https://user-images.githubusercontent.com/11253903/184271742-7ee05dd4-8347-4e1d-80b4-1000ba6f5e1f.png">
<img width="698" alt="Screen Shot 2022-08-12 at 10 09 30 AM" src="https://user-images.githubusercontent.com/11253903/184272103-06545cc0-f4fd-4355-a734-0bf4ede53316.png">

Maybe your browser is running Cached version of the app.
Can you retry after Refresh?

**Comment by sidhujag** [comment]
cache not an issue because other issues were fixed

**Comment by sidhujag** [comment]
How many accounts do you have? I think maybe if you have more than one pali account it always shows the "connected account" message and then signing never gets invoked

**Comment by osiastedian** [comment]
![Screen Shot 2022-08-15 at 10 39 07 PM](https://user-images.githubusercontent.com/11253903/184656378-9686cda6-6846-4ea8-8da4-e12027b3356b.png)

Currently have 2 accounts.

Will test in both and send demo videos here.

**Comment by osiastedian** [comment]
@sidhujag 

Multi-account Demo
https://user-images.githubusercontent.com/11253903/184929928-e7564199-c2af-4a76-9386-d0dd6baa0e1e.mov

I'll continue to investigate maybe I'm missing something.

**Comment by sidhujag** [comment]
Try it a few times until you get the account selection screen instead of the signature

**Comment by osiastedian** [comment]
Hi @sidhujag ,

I tried doing it a few time. I was able to reproduce it.
Not sure what other options we can have.
https://user-images.githubusercontent.com/11253903/185437515-01ff85ef-9ed4-4381-8350-3edaff6b586a.mov

**Comment by osiastedian** [comment]
Closing issue. Current behavior: Opens pali asking them to unlock
