### ISSUE TITLE
[BUG] Tries to Resign when Resuming from Burn Sys state

### ISSUE THREAD

**Issue by osiastedian** [osiastedian/syscoin-bridge#2]
Steps:

1. Open a new transfer
2. Input valid amount ex. 0.1
3. Click "Start Transfer"
4. Sign "burn sys" transaction on PaliWallet
5. Immediately go to "Transfers" Page
6. Resume the transaction you were doing by clicking the Transaction Id

Actual Result:

1. Bridge prompts to resign burn-sys transaction

Expected Result:

1. Should just continue to burn sysx state

**Comment by sidhujag** [comment]
Looks good!
