### ISSUE TITLE
Change Address issue

### ISSUE THREAD

**Issue by nrhs05** [osiastedian/syscoin-bridge#21]
Essentially, I started a transfer and did the sys to sysx, and burned sysx txs. Afterwards I opened up Pali to do other things and sent a transaction, afterwards it changed the default sending-address after sending a transfer, and now I cant go back and finish my pending (burned sysx in my wallet) as the bridge doesnt see my previous transactions anymore due to my main pali address changing.

**Comment by osiastedian** [comment]
> Afterwards I opened up Pali to do other things and sent a transaction

Did you switch to another account on PaliWallet when doing this?

**Comment by nrhs05** [comment]
> > Afterwards I opened up Pali to do other things and sent a transaction
> 
> Did you switch to another account on PaliWallet when doing this?

Nope, Pali generated a new change address in my main account the moment I opened the pali window manually, I seen the bridge history dissappear as it did it. Weird as it should only generate a change address when you make a transaction... maybe it was because of the burns tx triggering it making a new change address or something

**Comment by osiastedian** [comment]
Sorry @nrhs05 I'm still confused on the scenario when you say:
> it changed the default sending-address after sending a transfer

If you don't mind can you attach a video of the issue.

**Comment by nrhs05** [comment]
> Sorry @nrhs05 I'm still confused on the scenario when you say:
> 
> > it changed the default sending-address after sending a transfer
> 
> If you don't mind can you attach a video of the issue.

I'll try and attach a video later If I can replicate it if it easy enough, but essentially Pali wallet is not like metamask in the sense that it does not always keep the same sys1 address, as metamask keeps its same 0x address forever. Pali uses utxo change addresses so it will change its address to an unused address after an address has already been used, it should do it immediately not sure if it does or what triggers it exactly.

So what happens is the bridge is looking for a sys1 address that belongs to the account in Pali, on its xpub, but is no longer listed as it's receiving address which is what the bridge looks at to find any non finished bridge transfers.

I had to manually copy the TX from Pali and finish it on the old bridge.

You can view associated addresses by searching the xpub from Pali in elint blockbook explorer.

**Comment by fintroll20** [comment]
Here is a quick way to reproduce @nrhs05 issue.
Basically Pali changes it's receiving address after every confirmed transaction, even the bridge transactions.

Let's start with connecting Pali to the dapp with address **sys1qkr86hkq2kaetpu52hwrn82dlgvy8jsg9l4vkhc**:

![1](https://user-images.githubusercontent.com/56633605/195018124-ef911e1b-d8d7-4080-a85a-b6482c19de55.jpg)
[](url)
![2](https://user-images.githubusercontent.com/56633605/195018512-ae8a37da-9a03-4648-a5cd-cc23f446a89d.jpg)


After signing the requests to burn SYS, close the dapp. Wait for confirmations.
After the transactions are confirmed (or maybe even before that) close the browser completely. (This can also be reproduced by changing Pali accounts, or probably just locking it for a few minutes)
Open it up again, unlock Pali, click on 'Receive'. You will see, a new address has been generated.
![5](https://user-images.githubusercontent.com/56633605/195018792-9773e7f5-6e8d-468e-9ae0-fc8abf2256bd.jpg)

Connect to the dapp again with the new address, transaction history is empty, can't complete previous attempt.
![6](https://user-images.githubusercontent.com/56633605/195018916-5f45576c-1884-40f3-be5e-433f97ec4ada.jpg)
![7](https://user-images.githubusercontent.com/56633605/195018945-2d6d4d44-1f9f-4437-b746-99145c18735d.jpg)

**Comment by sidhujag** [comment]
It should be looking at xpub for history NOT address, thought it was doing this already. We covered this early on.

**Comment by osiastedian** [comment]
Hi @fintroll20  and @nrhs05 ,

I've added my test fix regarding this issue.
We have now use zpub as reference for saving transactions.

https://syscoin-bridge-git-21-change-address-issue-osiastedian.vercel.app/

You can view changes involved if you want to check it out.
https://github.com/osiastedian/syscoin-bridge/pull/27

Will merge this early next week please let me know any feedback. :D

**Comment by nrhs05** [comment]
Working great for me in Firefox, so far, except for after the burn it seems to be stuck waiting for confirmation even though its been confirmed already. Chrome is still a mess with trying to connect the wallet, but that is a pali issue not an issue with the bridge.

two burn txids:
78f827671fae33e16b34a394974bbcec299c4123de61a748da693fab3a30dcd9
eb75e13ddc8e6216dc751b8bf0fe67bdd429dc1d8e3a0d89c74e5ab586887ded

zpub of wallet:
zpub6qmt9aSfKDmTuWov7xZ9yBSryyQMeGa3c3JvU1J4ULEw2G5tNr5PnLDkpXoHWUBpedb17FQ2Q8gHycabsoqV3zQ3fq6YkhXtCWFD33A9Fko

transfer id is:
1665668752115

![image](https://user-images.githubusercontent.com/6243414/195627719-c135f7eb-6795-4c8b-bca7-813f128aab4d.png)

**Comment by fintroll20** [comment]
Seems to work fine for me now.. atleast for new transactions
But it doesn't import previous ones, right? 
So, is there I way I can complete all the previous transactions I started prior to this update?

Also this issue @nrhs05 mentioned:

> except for after the burn it seems to be stuck waiting for confirmation even though its been confirmed already.

Was reported yesterday by a different user on the old version. 
[See Here](https://bridge.syscoin.org/bridge/1665603298354)

If you could add an option to manually finish the transactions via transactions ID (e.g. the old bridge) it would probably solve all remaining problems.

**Comment by function0xMarki** [comment]
@fintroll20 
> If you could add an option to manually finish the transactions via transactions ID (e.g. the old bridge) it would probably solve all remaining problems.

Yes, there is the possibility of going to bridgev1 to finish your previous transactions, or in case of any inconvenience.
To access the bridge v1 you just have to replace the **bridge**.syscoin.org subdomain with **bridgev1**.syscoin.org

**Comment by osiastedian** [comment]
Closing issue with fix on #27
