### ISSUE TITLE
Add Rollux Support

### ISSUE THREAD

**Issue by osiastedian** [osiastedian/syscoin-bridge#23]
As a User, I would like to be able to transfer my SYS to rSYS on Rollux L2 Chain
so that I would be able to do transactions on Rollux.

Todos:

- [ ] Remove switch toggle
- [ ] Change bridge chain selection to use Dropdown
- [ ] Add "Rollux" on Destination list
- [ ] Add handling of Rollux

**Comment by sidhujag** [comment]
shall we call it just L1 SYS to L2 SYS or something? it is SYS after all what sort of naming convention to use? because if iwe use rSYS then metamask doesn't show price information in the send dialog

**Comment by osiastedian** [comment]
Done on separate Repo.
