### ISSUE TITLE
Wallets installation links.

### ISSUE THREAD

**Issue by function0xMarki** [osiastedian/syscoin-bridge#28]
The 2 Metamask and Pali Wallet icons appear on the home page, with the other "Launch Icon".

Both links point directly to the Chrome web store extension repository.

In this case, we assume that users will be using a Chromium-type web browser, and therefore Firefox users will not have access to install the extensions directly.

Perhaps we should link directly to their official extension websites, where the user can choose what type of web browser they use.

Therefore, the links to the official urls of each extension would be updated.

https://paliwallet.com/
https://metamask.io/

**Comment by osiastedian** [comment]
@function0xMarki 

This should now be fixed on main bridge site. :D
