### ISSUE TITLE
Metamask connect message doesn't go away

### ISSUE THREAD

**Issue by sidhujag** [osiastedian/syscoin-bridge#3]
After refresh the messages pop up to connect, after connecting the metamask one doesn't go away
<img width="1792" alt="Screen Shot 2022-08-10 at 1 04 13 PM" src="https://user-images.githubusercontent.com/6238042/184012228-1584832c-36ed-4df6-b064-22c56feb12fe.png">
Metamask is set to NEVM network and **switch** doesn't do anything. If i switch network manually and hit the switch button then it asks correctly to switch and goes away.. but otherwise that message is stuck there not going away.

**Comment by osiastedian** [comment]
@sidhujag 

Demo:

https://user-images.githubusercontent.com/11253903/184129338-df69cb7f-4d9f-4cfe-8c4b-58c4a7966d06.mov

**Comment by sidhujag** [comment]
not sure what this video is supposed to show

**Comment by sidhujag** [comment]
looks ok, video doesn't show anything but looks good when i tested
