### ISSUE TITLE
NEVM to SYS wizard: on SYS/SYSX signatures the screen doesn't update to "waiting for confirmations" right away like SYS to NEVM wizard

### ISSUE THREAD

**Issue by sidhujag** [osiastedian/syscoin-bridge#4]
Quirk on the NEVM to SYS signatures... it takes a few seconds for the state to update.. so after the second signature user is confused what is happening because the screen says check Pali and hitting retry will ask for signature again, if you don't do anything it will change state after it finds the tx in blockbook but just in mean-time the message is confusing (going from SYS TO NEVM doesn't have this issue it properly updates to "waiting for confirmations" right away after Pali signature box is closed)
<img width="1386" alt="Screen Shot 2022-08-10 at 1 04 16 PM" src="https://user-images.githubusercontent.com/6238042/184013014-b88cd731-16d8-4e78-9319-d2dc0206bda4.png">

**Comment by osiastedian** [comment]
Fix deployed on https://syscoin-bridge.vercel.app/

**Comment by sidhujag** [comment]
looks good!
