### ISSUE TITLE
500 error when loading my transfers

### ISSUE THREAD

**Issue by sidhujag** [osiastedian/syscoin-bridge#6]
Just refreshed and connected wallets, get 500:
<img width="1792" alt="Screen Shot 2022-08-20 at 10 10 09 AM" src="https://user-images.githubusercontent.com/6238042/185764546-f4a8cfba-a242-43c4-a8a5-9bfdd79dfe53.png">

**Comment by sidhujag** [comment]
Query: https://syscoin-bridge.vercel.app/api/transfer?utxo=tsys1q6ljulry9zzeg2hddy5s7wrtgch4hrczhnnmtqw&nevm=0xc1d5c0b84253f8af0aa3c73d3ff09fc07b033893

**Comment by osiastedian** [comment]
Yeah this was firebase timing out.

![Screen Shot 2022-08-23 at 9 46 36 PM](https://user-images.githubusercontent.com/11253903/186174773-87517e3d-9534-42c2-9c00-d5986588d81e.png)

Will try to reproduce locally.

**Comment by osiastedian** [comment]
Should work now @sidhujag 
![Screen Shot 2022-08-23 at 10 25 12 PM](https://user-images.githubusercontent.com/11253903/186183957-dc017fdc-acb9-4b5a-8e57-c2003c62f196.png)

**Comment by sidhujag** [comment]
how was it intermittent before? It would work sometimes without auth? Or maybe that was cached screens showing.

**Comment by osiastedian** [comment]
@sidhujag 

Yeah before it was on test mode where everyone can read and write. Now only the server has read and write access.
